name: Sync with Upstream

on:
  schedule:
    # 00:00 UTC every Monday
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/golang/tools.git
          git fetch upstream

      - name: Create sync branch
        run: |
          # Create a new branch with a timestamp
          SYNC_BRANCH="sync-upstream-$(date +%Y%m%d-%H%M%S)"
          git checkout -b $SYNC_BRANCH upstream/master
          echo "SYNC_BRANCH=$SYNC_BRANCH" >> $GITHUB_ENV

      - name: Replace module name
        run: |
          # Find and replace all occurrences of golang.org/x/tools with github.com/block/ftl-golang-tools
          find . -type f -name "*.go" -o -name "*.mod" -o -name "*.sum" -o -name "*.md" | xargs sed -i 's|golang\.org/x/tools|github.com/block/ftl-golang-tools|g'
          
          # Special handling for go.mod
          sed -i 's|^module golang\.org/x/tools$|module github.com/block/ftl-golang-tools|g' go.mod

      - name: Commit changes
        run: |
          git add .
          git commit -m "Sync with upstream and update module paths"

      - name: Push branch
        run: |
          git push origin $SYNC_BRANCH

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Sync with upstream golang/tools"
          body: |
            This PR syncs changes from the upstream repository (golang/tools) and updates all module paths.
            
            - Synced with latest upstream changes
            - Replaced all occurrences of `golang.org/x/tools` with `github.com/block/ftl-golang-tools`
            
            This PR was created automatically by the sync-upstream workflow.
          branch: ${{ env.SYNC_BRANCH }}
          base: master
          labels: automated-pr, sync-upstream
          draft: false

      - name: Enable auto-merge
        if: steps.create-pr.outputs.pull-request-number
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}
          merge-method: merge 
